services:
  # -----------------
  # DATABASE SERVICES
  # -----------------
  postgres:
    image: postgres:latest
    container_name: custom-shop-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - custom-shop-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: custom-shop-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - custom-shop-network

  # -------------
  # JAVA API (Backend)
  # -------------
  custom-shop-api:
    container_name: custom-shop-api
    build:
      context: ${BACKEND_DIR}
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DDL_AUTO: "update"
      PRODUCT_IMAGES_BASE_PATH: "/api/files/"
      PRODUCT_IMAGES_UPLOAD_DIR: "uploads"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "50MB"
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "100MB"
      # SPRING_APPLICATION_JSON: '{
      #   "logging.level.root": "INFO",
      #   "logging.level.org.springframework.web": "DEBUG"
      # }'
    ports:
      - "8080:8080"
    networks:
      - custom-shop-network

networks:
  custom-shop-network:
    driver: bridge

volumes:
  postgres_data: